version: '3.7'

services:
  app:
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        # replace for your personal access token
        - PAT=4cz7ryqwngmvfkskbyp4id54xpll5muejgffa5ib5zjwv4svsmyq
    sysctls:
      - net.core.somaxconn=1024
      - net.ipv4.tcp_syncookies=0
    ulimits:
      nproc: 95535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
    - ./:/app
    - /var/run/docker.sock:/var/run/docker.sock    
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /app
    entrypoint: make all

  eventstore:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
